/** The `Invoices/Invoices.md` index — pure, shared by the plugin and the CLI,
 *  so an invoice written from a terminal lands in the same table as one made
 *  from the command palette. */
import { money } from "./model";

export const INDEX_NAME = "Invoices";
export const TABLE_START = "<!-- INVOICE-TABLE:START -->";
export const TABLE_END = "<!-- INVOICE-TABLE:END -->";

export interface IndexRow {
  basename: string;
  fm: Record<string, string | undefined>;
}

function amount(raw: string, symbol: string): string {
  const n = Number(raw);
  return Number.isFinite(n) ? `${symbol}${money(n)}` : `${symbol}${raw}`;
}

export function buildIndexTable(rows: IndexRow[]): string {
  const body = rows.map(({ basename, fm }) => {
    const total = fm.total_cny
      ? amount(fm.total_cny, "¥")
      : fm.total_usd
        ? amount(fm.total_usd, "$")
        : fm.total_usd_priced
          ? amount(fm.total_usd_priced, "$")
          : "—";
    const paid = fm.paid_date ? `✅ ${fm.paid_date}` : "❌ unpaid";
    return `| \`${fm.invoice_number ?? basename}\` | ${fm.bill_to ?? "—"} | ${
      fm.issued ?? "—"
    } | ${total} | ${paid} | [[${basename}]] |`;
  });

  return [
    TABLE_START,
    "| No. | Bill to | Issued | Amount | Paid? | Invoice |",
    "|---|---|---|---:|---|---|",
    ...(body.length ? body : ["| — | — | — | — | — | *no invoices yet* |"]),
    TABLE_END,
  ].join("\n");
}

/** Splice a fresh table into an existing index, leaving the prose alone. */
export function spliceIndex(existing: string, table: string): string {
  const start = existing.indexOf(TABLE_START);
  const end = existing.indexOf(TABLE_END);
  if (start === -1 || end === -1) {
    return existing.trimEnd() + "\n\n" + table + "\n";
  }
  return existing.slice(0, start) + table + existing.slice(end + TABLE_END.length);
}

export function indexSkeleton(table: string): string {
  return `---
tags:
  - finance
  - meta
  - invoice
type: invoice-index
---

# 🧾 Invoices

Every invoice this vault has issued. Generated by **State Street Invoicer** — do not hand-edit
between the markers; the table is rewritten each time an invoice is created.

> [!caution] An invoice is a bill, not a receipt
> "Issued" means the document exists. Repayment lives where the obligation lives — \`paid_date\`
> on the item notes for an IOU (then re-run \`build_ious.py\`), or the Applied Badminton sales
> ledger in Berkshire for a stringing job.

${table}

**See also:** [[Debts & IOUs]] · [[IOU Index]]

---
**Hub:** [[Home]]
`;
}

/** Next `PREFIX-YYYY-NNNN`, counted from the basenames already in the folder. */
export function nextNumberFrom(
  basenames: string[],
  prefix: string,
  year: string,
): string {
  const re = new RegExp(`^${prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}-${year}-(\\d+)`);
  let max = 0;
  for (const b of basenames) {
    const m = b.match(re);
    if (m) max = Math.max(max, Number(m[1]));
  }
  return `${prefix}-${year}-${String(max + 1).padStart(4, "0")}`;
}
